<? $web = new web((object) array( 	
													"page_title" => "Lost password",
													"meta_description" => "Lost password",
													"model" => "user",
													"control" => "user",
													"theme" => "admin",
													"level" => 0 
												)); ?>
															
<h1>Lost password</h1>

<?if ($web->message != "" ) { ?>
	
	<h2><?=$web->message?></h2>
	
<? } else { ?>
	
	<form id="webForm" enctype="multipart/form-data" method="post">
		
		<p class="field">
			<label><?=$web->t('E-mail')?></label>
			<input type="text" id="email" name="email" value="<?=$user->email?>" class="text input" />
		</p>
	
		<input type="hidden" id="webAction" name="webAction" value="lostpassword" />
		<input type="hidden" id="webObject" name="webObject" value="user" />
		
		<div class="medium danger icon-right icon-forward btn entypo" style="float: right"><a href="#" onclick="$('#webForm').submit();" ><?=$web->t("submit") ?></a></div>
	
	</form>
	
<? } ?>

<div class="small default btn"><a href="/login"><?=$web->t('Sign in')?></a></div>
