<? $web = new web((object) array(	
													"page_title" => "Users",
													"model" => "user",
													"control" => "user",
													"theme" => ((!$_POST)?'admin':'blank'),
													"level" => 100
												)); ?>
													
<h1 class="webTitle">
	<?=$web->t("users") ?>
	<div class="small default btn icon-left entypo icon-plus"><a href="#" onclick="webWindowLoad('user',0);" ><?=$web->t("Add") ?></a></div>
	<div class="small default btn icon-left entypo icon-search"><a href="#" onclick="webFiltersToggle();" ><?=$web->t("Filters") ?></a></div>
</h1>

<? $web->filterBy(  json_decode('{
													 	"name": { "type": "text", "default": "", "value": "'.$user->name.'" },
													    "email": { "type": "text", "default": "", "value": "'.$user->email.'" },
													    "user": { "type": "text", "default": "", "value": "'.$user->user.'" },
													    "active": { "type": "checkbox", "default": "1", "value": "'.$user->active.'" },
													    "level": { "type": "select", "default": { "All":"", "Guest":"10", "User":"50", "Admin":"100" }, "value": "'.$user->level.'" }
													}') );  ?>

<table class="striped">
	
	<thead>
		<tr>
			<th class="info"><?=$web->t("id"); $web->orderBy('id'); ?> </th>
			<th><?=$web->t("user"); $web->orderBy('user'); ?></th>
			<th><?=$web->t("email"); $web->orderBy('email'); ?></th>
			<th style="width: 150px;"></th>
		</tr>
	</thead>
	
	<tbody>
		<? foreach( $users as $user ) { ?>
			<tr>
				<td><?=$user->id?></td>
				<td><?=$user->user?></td>
				<td><?=$user->email?></td>
				<td>
					<div class="small info btn icon-left entypo icon-pencil"><a href="javascript: webWindowLoad('user','<?=$user->id?>');" ><?=$web->t("Edit")?></a></div>
					<div class="small info btn icon-left entypo icon-trash"><a href="javascript: webRemove('user','<?=$user->id?>');" ><?=$web->t("Delete")?></a></div>
				</td>
			</tr>
		<? }?>
	</tbody>

</table>

<? $web->pagination( $web->user ); ?>
