<!doctype html>
<html lang="<?=$this->language ?>">
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en" itemscope itemtype="http://schema.org/Product"> <!--<![endif]-->
<head>
	
	<meta charset="<?=$this->charset ?>"> 
	<meta http-equiv="content-language" content="<?=$this->language ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

	<title><?= $this->full_title ?></title>
	<meta name="copyright" content="Quarkcode" />
	<meta name="author" content="Quarkcode - www.quarkcode.com" /> 
	<META NAME='ROBOTS' CONTENT='NOINDEX, NOFOLLOW' />

	<link rel="shortcut icon" href="/img/favicon.png" type="image/x-icon" />
	<link type="text/css" href="/css/gumby.css" rel="stylesheet" />
	<link type="text/css" href="/css/style.admin.css" rel="stylesheet" />

	<script src="/js/jquery/jquery.js"></script>
	<script src="/js/jquery/jquery-migrate.js"></script>
	<script src="/js/jquery/jquery-ui.js"></script>
    <script src="/js/jquery/modernizr.js" type="text/javascript"></script>
    <script src="/js/functions.admin.js" type="text/javascript"></script>
	
	<?=$this->head ?>
	
</head>

<body class="metro">
	
	<div class="row">
		<div class="twelve columns special head">
			<? $this->layout('head') ?>
		</div>
	</div>
	
	<div class="row">
		<div id="sidebar" class="two columns">
			<? $this->layout('sidebar') ?>
		</div>
		<div  id="content" class="ten columns">
			<?=$this->content ?>
		</div>
	</div>

	<script src="/js/gumby/gumby.js" type="text/javascript"></script>
	<script src="/js/gumby/gumby-plugins.js" type="text/javascript"></script>
	<script src="/js/gumby/gumby-main.js" type="text/javascript"></script>
	
</body>

</html>