<!doctype html>
<html lang="<?=$this->language ?>">
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en" itemscope itemtype="http://schema.org/Product"> <!--<![endif]-->
<head>
	
	<meta charset="<?=$this->charset ?>"> 
	<meta http-equiv="content-language" content="<?=$this->language ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

	<title><?= $this->full_title ?></title>

	<!-- Meta -->

		<meta name="keywords" content="<?=$this->meta_keywords ?>" />
		<meta name="abstract" content="<?=$this->meta_description ?>" />
		<meta name="description" content="<?=$this->meta_description ?>" />
		<meta name="copyright" content="" />
		<meta name="author" content="" /> 
		
		<!-- Meta Facebok -->
		<meta property="og:title" content="<?=$this->full_title ?>" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="http://<?=$this->domain ?>/" />
		<meta property="og:site_name" content="<?=$this->full_title ?>" />
		<meta property="og:image" content="http://<?=$this->domain ?>/img/image.png"/>
		<meta property="og:description" content="<?=$this->meta_description ?>" />
		
		<!-- Meta Google+ -->
		<meta itemprop="name" content="<?=$this->full_title ?>">
		<meta itemprop="description" content="<?=$this->full_title ?>">
		<meta itemprop="image" content="http://<?=$this->domain ?>/img/image.png">

	<!-- //Meta -->

	<link rel="shortcut icon" href="/img/favicon.png" type="image/x-icon" />
	<link type="text/css" href="/css/gumby.css" rel="stylesheet" />
	<link type="text/css" href="/css/style.css" rel="stylesheet" />

	<script src="/js/jquery/jquery.js"></script>
	<script src="/js/jquery/jquery-migrate.js"></script>
	<script src="/js/jquery/jquery-ui.js"></script>
    <script src="/js/jquery/modernizr.js" type="text/javascript"></script>
    <script src="/js/functions.js" type="text/javascript"></script>
	
	<?=$this->head ?>
	
</head>

<body>
	
	<div class="row">
		<div class="twelve columns special head">
			<? $this->layout('head') ?>
		</div>
	</div>

	<div class="row">
		<div id="sidebar" class="one columns">
			<? $this->layout('sidebar') ?>
		</div>
		<div  id="content" class="eleven columns">
			<?=$this->content ?>
		</div>
	</div>

	<script src="/js/gumby/gumby.js" type="text/javascript"></script>
	<script src="/js/gumby/gumby-plugins.js" type="text/javascript"></script>
	<script src="/js/gumby/gumby-main.js" type="text/javascript"></script>
	
	<!-- Google Analitycs: Change UA-XXXXX-X to be your site's ID -->
	<!--<script>
	window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
	Modernizr.load({
		load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	});
	</script>-->

</body>

</html>